apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: punsbot-dev
spec:
  destination:
    namespace: punsbot-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cicd/kustomize
    repoURL: https://github.com/punsbot/app.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
