apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: punsbot
  name: punsbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: punsbot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: punsbot
      name: punsbot
    spec:
      containers:
      - env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: TOKEN
              name: telegram-token-secret
        - name: DBLOCATION
          value: /var/punsdb/punsdb.db
        image: quay.io/soukron/punsbot:dev
        imagePullPolicy: Always
        name: punsbot
        resources:
          limits:
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/punsdb
          name: database-mount
      volumes:
      - name: database-mount
        persistentVolumeClaim:
          claimName: database
