apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: punsbot-pro
  namespace: argocd
spec:
  destination:
    namespace: punsbot-pro
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy/argocd/pro
    repoURL: 'https://github.com/soukron/punsbot'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

