apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: punsbot
    name: telegram-token-secret
  stringData:
    token: NjMyMDc0MjQ3OkFBRnh4blg3aFdheTVWMUFVZXdVYjFoRVF

